project_id = "ufcarzzouvxgqljqxdnc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ufcarzzouvxgqljqxdnc.supabase.co"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
s3_max_part_size = "5MiB"
s3_upload_part_size = "5MiB"
s3_multipart_threshold = "20MiB"

[edge_runtime]
enabled = true
port = 54324
inspector_port = 8083

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54325

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[functions.create-user-bucket]
verify_jwt = false

[functions.evolution-connection-events]
verify_jwt = false

[functions.sync-evolution-status]
verify_jwt = false